homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 5
  unit_system: imperial
  time_zone: America/New_York
  customize: !include customize.yaml

map:

zone:
  - name: home
    latitude: !secret latitude
    longitude: !secret longitude
    radius: 200

proximity:
  home:
    devices:
      - !secret gtracker_one
      - !secret gtracker_two
    tolerance: 100
    unit_of_measurement: mi

cloud:

lovelace:

customizer:
  custom_ui: local

frontend:
  themes: !include themes.yaml
  extra_html_url:
    - /local/custom_ui/custom-weather-card.html
    - /local/custom_ui/state-card-floorplan.html
  extra_html_url_es5:
    - /local/custom_ui/custom-weather-card.html

panel_custom:
  - name: floorplan
    sidebar_title: Floor Plan
    sidebar_icon: mdi:floor-plan
    url_path: floorplan
    config: !include floorplan.yaml

weather:
  - platform: darksky
    api_key: !secret dark_sky_api_key
    mode: daily

input_boolean:
  bedtime_sean:
    name: Sean Bedtime
    initial: false

  bedtime_emily:
    name: Emily Bedtime
    initial: false

  sean_office_presence:
    name: Sean Office Presence
    initial: false

  sean_living_room_presence:
    name: Sean Living Room Presence
    initial: false

  sean_bedroom_presence:
    name: Sean Bedroom Presence
    initial: false

  emily_office_presence:
    name: Emily Office Presence
    initial: false

  emily_living_room_presence:
    name: Emily Living Room Presence
    initial: false

  emily_bedroom_presence:
    name: Emily Bedroom Presence
    initial: false

sun:

# BEGIN CONFIG
config:
http:
  api_password: !secret api_password
  base_url: !secret base_url
  ip_ban_enabled: true
  cors_allowed_origins:

updater:

# Discover some devices automatically
discovery:
  ignore:
    - roku

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

# Enables support for tracking state changes over time
history:
  include:
    domains:
      - switch
    entities:
      - light.bathroom
      - light.bedroom
      - light.living_room
      - light.office
      - device_tracker.androidb5fd101061eefa11
      - device_tracker.android92a8793ea8df7b4e
      - sensor.living_room_thermostat_hvac_state
      - sensor.living_room_thermostat_temperature
      - sensor.bedroom_temperature_f
      - sensor.office_temperature_f
      - sensor.dark_sky_temperature

recorder:
  purge_interval: 1
  purge_keep_days: 7
  include:
    domains:
      - switch
    entities:
      - light.bathroom
      - light.bedroom
      - light.living_room
      - light.office
      - device_tracker.androidb5fd101061eefa11
      - device_tracker.android92a8793ea8df7b4e
      - sensor.living_room_thermostat_hvac_state
      - sensor.living_room_thermostat_temperature
      - sensor.bedroom_temperature_f
      - sensor.office_temperature_f
      - sensor.dark_sky_temperature

# View all events in a logbook
logbook:

### SENSORS ###
sensor:
  - platform: template
    sensors:
      hue:
        value_template: '{% if is_state("device_tracker.philipshue", "home") %}Online{% else %}Offline{% endif %}'
        friendly_name: 'Hue Bridge'

  - platform: template
    sensors:
      bathroom_temperature:
        value_template: '{{states.sensor.bathroom_motion_sensor.attributes.temperature}}'

  - platform: template
    sensors:
      bathroom_battery:
        friendly_name: 'Battery'
        value_template: '{{states.sensor.bathroom_motion_sensor.attributes.battery}}'
        unit_of_measurement: '%'

  - platform: template
    sensors:
      bathroom_temperature_f:
        friendly_name: 'Bathroom Temperature'
        entity_id:
          - sensor.bathroom_temperature
        unit_of_measurement: °F
        value_template: >
          {{ ((float(states('sensor.bathroom_temperature')) * 1.8) + 32) | round(1) }}

  - platform: template
    sensors:
      phone_socket:
        friendly_name: 'Phone Power'
        value_template: '{{states.switch.smart_plug_one.attributes.current_power_w}}'

  - platform: template
    sensors:
      office_temperature:
        value_template: '{{states.sensor.office_motion_motion_sensor.attributes.temperature}}'

  - platform: template
    sensors:
      office_battery:
        friendly_name: 'Battery'
        value_template: '{{states.sensor.office_motion_motion_sensor.attributes.battery}}'
        unit_of_measurement: '%'

  - platform: template
    sensors:
      office_temperature_f:
        friendly_name: 'Office Temperature'
        entity_id:
          - sensor.office_temperature
        unit_of_measurement: °F
        value_template: >
          {{ ((float(states('sensor.office_temperature')) * 9 / 5) + 32) | round(1) }}

  - platform: template
    sensors:
      office_lux:
        friendly_name: 'Lux'
        value_template: '{{states.sensor.office_motion_motion_sensor.attributes.lx}}'

  - platform: template
    sensors:
      laptop_socket:
        friendly_name: 'Laptop Power'
        value_template: '{{states.switch.laptop_socket.attributes.current_power_w}}'

  - platform: template
    sensors:
      sun_elevation:
        friendly_name: Sun Elevation
        value_template: '{{states.sun.sun.attributes.elevation}}'

  - platform: template
    sensors:
      bedroom_sean_gh_rssi:
        value_template: '{{ states.device_tracker.sean_bt_bedroom.attributes.rssi }}'

  - platform: template
    sensors:
      livingroom_sean_gh_rssi:
        value_template: '{{ states.device_tracker.sean_bt_living_room.attributes.rssi }}'

  - platform: template
    sensors:
      office_sean_gh_rssi:
        value_template: '{{ states.device_tracker.sean_bt_office.attributes.rssi }}'

  - platform: template
    sensors:
      sean_room_status:
        value_template: '{{ states.input_select.sean_room_location.state }}'
        friendly_name: 'Room Location'

  - platform: template
    sensors:
      bedroom_emily_gh_rssi:
        value_template: '{{ states.device_tracker.emily_bt_bedroom.attributes.rssi }}'

  - platform: template
    sensors:
      livingroom_emily_gh_rssi:
        value_template: '{{ states.device_tracker.emily_bt_living_room.attributes.rssi }}'

  - platform: template
    sensors:
      office_emily_gh_rssi:
        value_template: '{{ states.device_tracker.emily_bt_office.attributes.rssi }}'

  - platform: template
    sensors:
      emily_room_status:
        value_template: '{{ states.input_select.emily_room_location.state }}'
        friendly_name: 'Room Location'

  - platform: darksky
    api_key: !secret dark_sky_api_key
    update_interval: '00:05:00'
    monitored_conditions:
      - temperature
      - precip_probability
      - precip_type
      - humidity
      - cloud_cover
      - nearest_storm_distance
      - precip_intensity
      - wind_speed

  - platform: systemmonitor
    resources:
      - type: processor_use
      - type: disk_use_percent
        arg: /home
      - type: memory_use_percent
      - type: ipv4_address
        arg: eth0
      - type: network_in
        arg: eth0
      - type: network_out
        arg: eth0
      - type: last_boot

  - platform: pi_hole
    host: !secret pihole_ip
    monitored_conditions:
      - ads_blocked_today
      - ads_percentage_today
      - dns_queries_today
      - domains_being_blocked
      - unique_clients

  - platform: plex
    host: !secret plex_ip

  - platform: steam_online
    api_key: !secret steam_api
    accounts:
      - !secret steam_account

  - platform: speedtest
    hour:
      - 0
      - 6
      - 12
      - 18
    monitored_conditions:
      - ping
      - download
      - upload

  - platform: hue
    ip_address: !secret hue_ip
    token: !secret hue_token

  - platform: waze_travel_time
    origin: !secret travel_origin
    destination: !secret travel_destination
    region: 'NA'
    name: Work Commute

  - platform: season
    type: astronomical

  - platform: time_date
    display_options:
      - 'time'

  - platform: qbittorrent
    url: !secret qbit_http
    username: !secret qbit_user
    password: !secret qbit_password

# USPS Informed Delivery
#usps:
#  username: !secret usps_user
#  password: !secret usps_password
#  name: USPS
#  driver: 'chrome'

# Cameras
#camera:
#  - platform: usps

input_select:
  sean_room_location:
    name: Sean's Room Location
    options:
      - Bedroom
      - Living Room
      - Office
      - Away
      - Home

  emily_room_location:
    name: Emily's Room Location
    options:
      - Bedroom
      - Living Room
      - Office
      - Away
      - Home

# Nest Temperature
nest:
  client_id: !secret nest_id
  client_secret: !secret nest_secret

# Hue
light:
  - platform: hue
    host: !secret hue_ip
hue:
  bridges:
    - host: !secret hue_ip
      allow_hue_groups: true

# Wemo
wemo:
  static:
    - !secret wemo_ip

# Xiaomi
xiaomi_aqara:
  discovery_retry: 10
  gateways:
    - key: !secret xiaomi_key

# Switches
switch:
 - platform: tplink
   host: !secret tplink_switch_one_ip
 - platform: tplink
   host: !secret tplink_switch_two_ip
 - platform: tplink
   host: !secret tplink_switch_three_ip

# Text to speech
tts:
  - platform: google

# Device Tracking
asuswrt:
  host: !secret router_ip
  protocol: telnet
  port: 23
  username: !secret router_user
  password: !secret router_password

device_tracker:
#  - platform: asuswrt
#    host: !secret router_ip
#    protocol: telnet
#    port: 23
#    username: !secret router_user
#    password: !secret router_password
#    interval_seconds: 10

# Office Speaker
  - platform: googlehome
    host: 192.168.1.208
    rssi_threshold: -100
    interval_seconds: 2
    consider_home: 10
    new_device_defaults:
      track_new_devices: false

# Bedroom Speaker
  - platform: googlehome
    host: 192.168.1.149
    rssi_threshold: -100
    interval_seconds: 2
    consider_home: 10
    new_device_defaults:
      track_new_devices: false

# Living Room Speaker
  - platform: googlehome
    host: 192.168.1.38
    rssi_threshold: -100
    interval_seconds: 2
    consider_home: 10
    new_device_defaults:
      track_new_devices: false

  - platform: google_maps
    username: !secret googlemaps_user
    password: !secret googlemaps_password
    max_gps_accuracy: 200

# Media
media_player:
  - platform: plex
    entity_namespace: plex
    include_non_clients: false
    scan_interval: 1
    show_all_controls: false
    use_custom_entity_ids: false
    use_episode_art: false
    remove_unavailable_clients: false

# Neato Vacuum
neato:
  username: !secret neato_user
  password: !secret neato_password

# IFTTT
ifttt:
  key: !secret ifttt_key



##########################
scene: !include scenes.yaml
group: !include groups.yaml
automation: !include_dir_merge_list automations
script: !include scripts.yaml
