title: Home

resources:
  - url: /local/mini-graph-card-bundle.js?v=0.3.0
    type: module
  - url: /local/mini-media-player-bundle.js
    type: module

views:
  - path: default_view
    title: Home
    icon: 'mdi:home'
    badges: []
    cards:
      - type: horizontal-stack
        cards:
          - type: picture-glance
            title: Room Location
            entities:
              - sensor.sean_room_status
              - sensor.sean_phone_battery
            state_image:
              "home": /local/images/sean_16x9.jpg
              "not_home": /local/images/sean_16x9_gray.jpg
            entity: device_tracker.sean_phone
          - type: picture-glance
            title: Room Location
            entities:
              - sensor.emily_room_status
              - sensor.emily_phone_battery
            state_image:
              "home": /local/images/emily_16x9.jpg
              "not_home": /local/images/emily_16x9_gray.jpg
            entity: device_tracker.emily_phone
      - type: entities
        entities:
          - sensor.work_commute
      - type: horizontal-stack
        cards:
          - type: entity-button
            entity: switch.office_fan
            name: Office Fan
            icon: mdi:fan
            tap_action:
              action: toggle
          - type: entity-button
            entity: switch.smart_plug_one
            name: Air Freshener
            icon: mdi:flower
            tap_action:
              action: toggle
          - type: entity-button
            entity: switch.outside_lights
            name: Outside Lights
            icon: mdi:lightbulb
            tap_action:
              action: toggle
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: light
                entity: light.living_room
                name: Living Room Lights
              - type: light
                entity: light.bedroom
                name: Bedroom Lights
          - type: horizontal-stack
            cards:
              - type: light
                entity: light.bathroom
                name: Bathroom Lights
              - type: light
                entity: light.office
                name: Office Lights
          - type: horizontal-stack
            cards:
              - type: picture-entity
                entity: vacuum.rosie
                name: Rosie
                image: /local/images/neato.png
              - type: picture-entity
                entity: sensor.plex
                name: Plex
                image: /local/images/plex.png
      - type: vertical-stack
        cards:
          - type: thermostat
            entity: climate.living_room
          - type: horizontal-stack
            cards:
              - type: custom:mini-graph-card
                entities:
                  - sensor.bedroom_temp
                name: Bedroom
                line_color: '#2980b9'
                line_width: 6
                show:
                  fill: fade
              - type: custom:mini-graph-card
                entities:
                  - sensor.bathroom_temperature_f
                name: Bathroom
                line_color: '#b58e31'
                line_width: 6
                show:
                  fill: fade
              - type: custom:mini-graph-card
                entities:
                  - sensor.office_temperature_f
                name: Office
                line_color: '#b93829'
                line_width: 6
                show:
                  fill: fade
      - type: vertical-stack
        cards:
          - type: weather-forecast
            entity: weather.dark_sky
          - type: horizontal-stack
            cards:
              - type: custom:mini-graph-card
                name: Sun Elevation
                entities:
                  - sensor.sun_elevation
                line_color: '#b58e31'
                line_width: 4
              - type: custom:mini-graph-card
                name: Chance of Rain
                entities:
                  - sensor.dark_sky_precip_probability
                line_color: '#2980b9'
                line_width: 4
  - path: livingroom
    title: Living Room
    icon: 'mdi:sofa'
    badges: []
    cards:
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: custom:mini-graph-card
                entities:
                  - sensor.living_room_thermostat_temperature
                name: Living Room
                line_color: '#2980b9'
                line_width: 2
          - type: horizontal-stack
            cards:
              - type: light
                entity: light.living_room
              - type: custom:mini-graph-card
                entities:
                  - sensor.living_room_thermostat_humidity
                name: Humidity
                line_color: '#b58e31'
                line_width: 4
                hours_to_show: 24
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: entity-button
                entity: switch.outside_lights
                name: Outside Lights
                icon: mdi:lightbulb
                tap_action:
                  action: toggle
              - type: glance
                entities:
                  - binary_sensor.door_window_sensor_158d00023eb0bb
                  - binary_sensor.motion_sensor_158d0002047afe
      - type: custom:mini-media-player
        entity: media_player.plex_living_room_tv
        icon: mdi:television
        artwork: cover
      - type: custom:mini-media-player
        entity: media_player.googlehome0160
        icon: mdi:google-home
        artwork: cover
        show_tts: google
      - title: Neato Vacuum
        type: picture-entity
        entity: vacuum.rosie
        image: /local/images/neato2.png
  - path: bedroom
    title: Bedroom
    icon: 'mdi:hotel'
    badges: []
    cards:
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: custom:mini-graph-card
                entities:
                  - sensor.bedroom_temp
                name: Bedroom
                line_color: '#2980b9'
                line_width: 4
              - type: custom:mini-graph-card
                entities:
                  - sensor.bathroom_temperature_f
                name: Bathroom
                line_color: '#b93829'
                line_width: 4
          - type: horizontal-stack
            cards:
              - type: custom:mini-graph-card
                entities:
                  - sensor.bedroom_humidity
                name: Bedroom Humidity
                line_color: '#b58e31'
                line_width: 2
                hours_to_show: 24
          - type: horizontal-stack
            cards:
              - type: light
                entity: light.bedroom
              - type: light
                entity: light.bathroom
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: glance
                entities:
                  - binary_sensor.motion_sensor_158d000237a64a
                  - binary_sensor.bathroom_motion
                  - sensor.bathroom_battery
      - type: custom:mini-media-player
        entity: media_player.bedroom_tv
        icon: mdi:television
        artwork: cover
      - type: custom:mini-media-player
        entity: media_player.bedroom_speaker
        icon: mdi:google-home
        artwork: cover
        show_tts: google
  - path: office
    title: Office
    icon: 'mdi:keyboard'
    badges: []
    cards:
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: custom:mini-graph-card
                entities:
                  - sensor.office_temperature_f
                name: Office
                line_color: '#2980b9'
                line_width: 2
          - type: horizontal-stack
            cards:
              - type: light
                entity: light.office
              - type: custom:mini-graph-card
                entities:
                  - sensor.office_lux
                name: Illumination
                line_color: '#b58e31'
                line_width: 4
                hours_to_show: 24
      - type: horizontal-stack
        cards:
          - type: entity-button
            entity: switch.office_fan
            name: Office Fan
            icon: mdi:fan
            tap_action:
              action: toggle
          - type: entity-button
            entity: switch.smart_plug_one
            name: Air Freshener
            icon: mdi:flower
            tap_action:
              action: toggle
      - type: vertical-stack
        cards:
          - type: horizontal-stack
            cards:
              - type: glance
                entities:
                  - binary_sensor.office_motion
                  - sensor.office_battery
                  - sensor.laptop_socket
      - type: custom:mini-media-player
        entity: media_player.googlehome0353
        icon: mdi:google-home
        artwork: cover
        show_tts: google
  - path: settings
    title: Settings
    icon: 'mdi:settings'
    badges: []
    cards:
      - title: System
        type: entities
        entities:
          - sensor.processor_use
          - sensor.disk_use_percent_home
          - sensor.memory_use_percent
          - sensor.last_boot
        show_header_toggle: false
      - title: Pi-Hole
        type: entities
        entities:
          - sensor.pi_hole_ads_blocked_today
          - sensor.pi_hole_ads_percentage_blocked_today
          - sensor.pi_hole_dns_queries_today
          - sensor.pi_hole_domains_blocked
        show_header_toggle: false
      - title: Internet Speed
        type: entities
        entities:
          - sensor.speedtest_ping
          - sensor.speedtest_download
          - sensor.speedtest_upload
        show_header_toggle: false
      - title: BT RSSI
        type: entities
        entities:
          - sensor.bedroom_sean_gh_rssi
          - sensor.livingroom_sean_gh_rssi
          - sensor.office_sean_gh_rssi
          - sensor.bedroom_emily_gh_rssi
          - sensor.livingroom_emily_gh_rssi
          - sensor.office_emily_gh_rssi
        show_header_toggle: false
      - title: Input Booleans
        type: entities
        entities:
          - input_boolean.bedtime_sean
          - input_boolean.bedtime_emily
          - input_boolean.sean_bedroom_presence
          - input_boolean.sean_living_room_presence
          - input_boolean.sean_office_presence
          - input_boolean.emily_bedroom_presence
          - input_boolean.emily_living_room_presence
          - input_boolean.emily_office_presence
        show_header_toggle: false
  - path: auto
    title: Automations
    icon: 'mdi:creation'
    badges: []
    cards:
      - title: Home Automations
        type: entities
        entities:
          - automation.away_mode
          - automation.lights_on_in_the_evening
          - automation.nest_normal_mode
          - automation.nest_normal_mode_google_tracker
          - automation.voice_sean_is_home
          - automation.voice_emily_is_home
          - automation.morning_alarm_lights
          - automation.turn_on_air_fresh
          - automation.outside_lights_on_at_sunset
          - automation.outside_lights_off_at_ten
        show_header_toggle: true
      - title: Room Presence
        type: entities
        entities:
          - automation.sean_in_bedroom
          - automation.sean_in_living_room
          - automation.sean_in_office
          - automation.sean_is_away
          - automation.emily_in_bedroom
          - automation.emily_in_living_room
          - automation.emily_in_office
          - automation.emily_is_away
        show_header_toggle: true
      - title: Living Room Automations
        type: entities
        entities:
          - automation.living_room_auto_brightness
          - automation.living_room_auto_brightness_transition
          - automation.living_room_lights_off_no_motion
          - automation.turn_off_living_room_lights_above_lux
          - automation.door_closed_turn_on_nest
          - automation.door_open_turn_off_nest
        show_header_toggle: true
      - title: Bedroom Automations
        type: entities
        entities:
          - automation.bedroom_auto_brightness
          - automation.bedroom_auto_brightness_transition
          - automation.bedroom_lights_off_no_motion
          - automation.bathroom_lights_on_motion
          - automation.bathroom_lights_on_motion_bedtime
          - automation.bathroom_lights_on_motion_early_morning
          - automation.bathroom_lights_off_no_motion
          - automation.bathroom_lights_off_no_motion_night
        show_header_toggle: true
      - title: Office Automations
        type: entities
        entities:
          - automation.office_auto_brightness
          - automation.office_auto_brightness_transition
          - automation.turn_on_fan_above_certain_temp
          - automation.turn_off_fan_below_certain_temp
          - automation.turn_off_office_fan_without_motion
          - automation.turn_off_office_lights_above_lux
          - automation.turn_office_lights_without_motion_one_min
        show_header_toggle: true
      - title: Media Automations
        type: entities
        entities:
          - automation.media_player_playing
          - automation.media_player_stopped
          - automation.media_player_paused
          - automation.media_player_unpaused
          - automation.media_player_pause_to_idle
          - automation.bedroom_player_playing
          - automation.bedroom_player_stopped
          - automation.bedroom_player_paused
          - automation.bedroom_player_unpaused
          - automation.bedroom_player_pause_to_idle
        show_header_toggle: true
