# Bathroom Lights on with Motion
- alias: Bathroom Lights on motion
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d000237a64a
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.family
        state: 'home'
      - condition: time
        after: '07:00:00'
        before: '22:00:00'
  action:
    service: light.turn_on
    data:
      entity_id: light.bathroom
      brightness_pct: '100'

# Bathroom Lights on with Motion at Bedtime
- alias: Bathroom Lights on motion bedtime
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d000237a64a
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.family
        state: 'home'
      - condition: time
        after: '22:00:00'
        before: '04:00:00'
  action:
    service: light.turn_on
    data:
      entity_id: light.bathroom
      brightness_pct: '1'

# Bathroom Lights on with Motion at Early Morning
- alias: Bathroom Lights on motion early morning
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d000237a64a
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.family
        state: 'home'
      - condition: state
        entity_id: light.bathroom
        state: 'off'
      - condition: time
        after: '04:00:00'
        before: '07:00:00'
  action:
    service: light.turn_on
    data:
      entity_id: light.bathroom
      brightness_pct: '100'
      transition: 60

# Bathroom Lights off without Motion
- alias: Bathroom Lights off no motion
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d000237a64a
    to: 'off'
    for:
      seconds: 30
  condition:
    - condition: numeric_state
      entity_id: sensor.humidity_158d0002478a21
      below: '67'
  action:
    service: light.turn_off
    data:
      entity_id: light.bathroom
      transition: 2

# Turn on air fresh for one minute each hour when home
#  - alias: Turn on air fresh
#    trigger:
#      platform: time
#      hours: '/1'
#      minutes: '00'
#      seconds: '00'
#    condition:
#      condition: and
#      conditions:
#        - condition: state
#          entity_id: group.family
#          state: 'home'
#        - condition: time
#          after: '06:00:00'
#          before: '22:15:00'
#    action:
#      - service: switch.turn_on
#        entity_id:  switch.smart_plug_one
#      - delay:
#          minutes: '10'
#      - service: switch.turn_off
#        entity_id:  switch.smart_plug_one
