# Sean Bedtime
- alias: Bedtime
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: script.turn_on
      entity_id: script.bedtime

# Emily Bedtime
- alias: Bedtime Emily
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: script.turn_on
      entity_id: script.bedtime_emily

# Sean Morning
- alias: Morning
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: script.turn_on
      entity_id: script.morning

# Emily Morning
- alias: Morning Emily
  trigger:
    platform: homeassistant
    event: start
  action:
    - service: script.turn_on
      entity_id: script.morning_emily

# Play Rain at Bedtime
#- alias: Rain Sounds
#  initial_state: off
#  trigger:
#    - platform: homeassistant
#      event: start
#    - platform: time
#      hours: '/1'
#      minutes: '00'
#      seconds: '00'
#  action:
#    - service: media_player.turn_on
#      data:
#        entity_id: media_player.office_speaker
#    - service: media_player.play_media
#      data_template:
#        entity_id: media_player.office_speaker
#        media_content_id: https://www.gstatic.com/voice_delight/sounds/long/rain.mp3
#        media_content_type: 'audio/mp3'

# Turn off Rain in morning
#- alias: Rain Sounds Off
#  trigger:
#    platform: homeassistant
#    event: start
#  condition:
#    - condition: and
#      conditions:
#        - condition: state
#          entity_id: input_boolean.bedtime_emily
#          state: 'off'
#        - condition: state
#          entity_id: input_boolean.bedtime_sean
#          state: 'off'
#  action:
#    - service: media_player.turn_off
#      data:
#        entity_id: media_player.office_speaker
#    - service: automation.turn_off
#      data:
#        entity_id: automation.rain_sounds
