# Living Room Lights on with Motion
- alias: Living Room Lights on motion
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d0002047afe
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.family
        state: 'home'
      - condition: numeric_state
        entity_id: sensor.illumination_158d0002047afe
        below: 6
      - condition: time
        after: '06:00:00'
        before: '19:00:00'
      - condition: template
        value_template: "{{ not is_state('media_player.living_room_tv', 'playing') }}" # NOT condition
  action:
    service: light.turn_on
    data:
      entity_id: light.living_room
      brightness: '255'

# Living Room Lights on with Motion 75
- alias: Living Room Lights on motion 75
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d0002047afe
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.family
        state: 'home'
      - condition: template
        value_template: "{{ not is_state('media_player.living_room_tv', 'playing') }}" # NOT condition
      - condition: numeric_state
        entity_id: sun.sun
        value_template: '{{ state.attributes.elevation }}'
        below: -6.0
        above: -15.0
  action:
    service: light.turn_on
    data:
      entity_id: light.living_room
      brightness: '190'

# Living Room Lights on with Motion 50
- alias: Living Room Lights on motion 50
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d0002047afe
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.family
        state: 'home'
      - condition: template
        value_template: "{{ not is_state('media_player.living_room_tv', 'playing') }}" # NOT condition
      - condition: numeric_state
        entity_id: sun.sun
        value_template: '{{ state.attributes.elevation }}'
        below: -15.0
        above: -25.0
  action:
    service: light.turn_on
    data:
      entity_id: light.living_room
      brightness: '128'

# Living Room Lights on with Motion at Bedtime
- alias: Living Room Lights on motion bedtime
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d0002047afe
    to: 'on'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: group.family
        state: 'home'
      - condition: template
        value_template: "{{ not is_state('media_player.living_room_tv', 'playing') }}" # NOT condition
      - condition: numeric_state
        entity_id: sun.sun
        value_template: '{{ state.attributes.elevation }}'
        below: -25.0
  action:
    service: light.turn_on
    data:
      entity_id: light.living_room
      brightness: '50'

# Living Room Lights off without Motion
- alias: Living Room Lights off no motion
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d0002047afe
    to: 'off'
    for:
      minutes: 13
  action:
    service: light.turn_off
    data:
      entity_id: light.living_room
      transition: 2

# Turn off Living Room lights above lux
- alias: Turn off living room lights above lux
  trigger:
    platform: numeric_state
    entity_id: sensor.illumination_158d0002047afe
    above: 115
  action:
    service: light.turn_off
    data:
      entity_id: light.living_room
      transition: 2
