# Living Room Lights on with Motion
- alias: Living Room Auto Brightness
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sensor_158d0002047afe
      to: 'on'
  condition:
    - condition: numeric_state
      entity_id: sensor.illumination_158d0002047afe
      below: '6'
    - condition: state
      entity_id: group.family
      state: 'home'
    - condition: state
      entity_id: light.living_room
      state: 'off'
    - condition: template
      value_template: "{{ not is_state('media_player.plex_living_room_tv_2', 'paused') }}" # NOT condition
    - condition: template
      value_template: "{{ not is_state('media_player.plex_living_room_tv_2', 'playing') }}" # NOT condition
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.living_room
        brightness_pct: '{% if states.sun.sun.attributes.elevation <= -35 %}10{% elif states.sun.sun.attributes.elevation <= -22 %}25{% elif states.sun.sun.attributes.elevation <= -15 %}50{% elif states.sun.sun.attributes.elevation <= -6 %}75{% elif states.sun.sun.attributes.elevation > -6 %}100{% else %}0{% endif %}'
    - delay:
        seconds: '1'
    - service: light.turn_on
      data_template:
        entity_id: light.living_room
        brightness_pct: '{% if states.sun.sun.attributes.elevation <= -35 %}10{% elif states.sun.sun.attributes.elevation <= -22 %}25{% elif states.sun.sun.attributes.elevation <= -15 %}50{% elif states.sun.sun.attributes.elevation <= -6 %}75{% elif states.sun.sun.attributes.elevation > -6 %}100{% else %}0{% endif %}'

# Auto Living Room Brightness Transition
- alias: Living Room Auto Brightness Transition
  initial_state: 'on'
  trigger:
    - platform: state
      entity_id: sun.sun
  condition:
    - condition: state
      entity_id: group.family
      state: 'home'
    - condition: state
      entity_id: light.living_room
      state: 'on'
  action:
    - service: light.turn_on
      data_template:
        entity_id: light.living_room
        brightness_pct: '{% if states.sun.sun.attributes.elevation <= -35 %}10{% elif states.sun.sun.attributes.elevation <= -22 %}25{% elif states.sun.sun.attributes.elevation <= -15 %}50{% elif states.sun.sun.attributes.elevation <= -6 %}75{% elif states.sun.sun.attributes.elevation > -6 %}100{% else %}0{% endif %}'
        transition: 30

# Living Room Lights off without Motion
- alias: Living Room Lights off no motion
  initial_state: 'on'
  trigger:
    platform: time
    minutes: '/5'
    seconds: 00
  condition:
    - condition: state
      entity_id: input_boolean.sean_living_room_presence
      state: 'off'
    - condition: state
      entity_id: input_boolean.emily_living_room_presence
      state: 'off'
    - condition: state
      entity_id: binary_sensor.motion_sensor_158d0002047afe
      state: 'off'
  action:
    - service: light.turn_off
      data:
        entity_id: light.living_room
        transition: 2
    - delay:
        seconds: '1'
    - service: light.turn_off
      data:
        entity_id: light.living_room
        transition: 2

# Turn off Living Room lights above lux
- alias: Turn off living room lights above lux
  initial_state: 'on'
  trigger:
    platform: numeric_state
    entity_id: sensor.illumination_158d0002047afe
    above: 115
  action:
    service: light.turn_off
    data:
      entity_id: light.living_room
      transition: 2
